
// 放送雑種パーツ
let atos_cross = [
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/honjitsumo_1.mp3", "本日も、ご利用いただき、ありがとうございます"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/kondono.mp3", "今度の"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/ressyaha.mp3", "列車は"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/densyaha.mp3", "電車は"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/yukitonatteorimasu.mp3", "行きとなっております"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/yukidesu.mp3", "行きです"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/yukito.mp3", "行きと"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/yukiha.mp3", "行きは"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/toekide.mp3", "当駅で"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/zoketsuwokonai.mp3", "増結を行います"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/zoketsuwoitashi.mp3", "増結をいたします"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/renketsu.mp3", "連結をいたします"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/maeyori.mp3", "前より"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/ushiroyori.mp3", "後ろ寄り"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/5ryoha.mp3", "5両は"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/10ryoha.mp3", "10両は"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/domari.mp3", "止まりとなります"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/yuki.mp3", "行き"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/yukino.mp3", "行きの"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/next.mp3", "次は"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/ni.mp3", "に"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/tomarimasu.mp3", "止まります"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/ressyaga.mp3", "列車が"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/tuka.mp3", "通過いたします"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/hassyasimasu.mp3", "発車いたします"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/konoressyaniha.mp3", "この列車には"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/konodensyaniha.mp3", "この電車には"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/jousya_node.mp3", "ご乗車になれませんので"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/jousya_naremasen.mp3", "ご乗車になれません"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/door_close.mp3", "ドアが閉まります"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/gochui.mp3", "ご注意ください"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/machiawase.mp3", "待合わせを行います"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/passmachi.mp3", "通過待ちをいたします"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/extraressyaga.mp3", "臨時列車が"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/kaisoressyaga.mp3", "回送列車が"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/dantairessyaga.mp3", "団体列車が"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/kamotuga.mp3", "貨物列車が"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/mamonaku.mp3", "まもなく"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/ressyagamairimasu.mp3", "列車がまいります"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/densyagamairimasu.mp3", "電車がまいります"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/yukiga.mp3", "行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/mairimasu.mp3", "まいります"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/homedoor_motare.mp3", "ホームドアから、手や顔を出したり、もたれかかるのはおやめください"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/abunai_homedoor.mp3", "危ないですから、ホームドアの後ろまで、お下がりください"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/abunai_tenji.mp3", "危ないですから、黄色い点字ブロックまで、お下がりください"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/abunai_sen.mp3", "危ないですから、黄色い線まで、お下がりください"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/kikendesukara.mp3", "危険ですから、黄色い線まで、お下がりください"],
  ["/users/yuki_tajima/desktop/メロディ.mp3", "接近メロディ"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/.mp3", ""],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/.mp3", ""],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/.mp3", ""],

]
// 列車種別
let train_type = [
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/local_1.mp3", "各駅停車"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/local_2.mp3", "普通"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/rapid.mp3", "快速"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/chuoutokkai.mp3", "中央特快"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/ometokkai.mp3", "青梅特快"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/comtokkai.mp3", "通勤特快"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/comrip.mp3", "通勤快速"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/tokkai.mp3", "特別快速"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/extra.mp3", "臨時"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/group.mp3", "団体"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/kaiso.mp3", "回送"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/junkyu.mp3", "準急"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/kaikyu.mp3", "快速急行"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/exp.mp3", "急行"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/ltdexp.mp3", "特急"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/nightltexp.mp3", "寝台特急"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/ohayoliner.mp3", "おはようライナー"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/homeliner.mp3", "ホームライナー"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/type/horide.mp3", "ホリデー快速"],
]
// 路線名
let train_line = [
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/syoshin.mp3", "湘南新宿ライン"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/joto.mp3", "上野東京ライン"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/chokutsu.mp3", "直通"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/mawari.mp3", "周り"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/takasaki.mp3", "高崎線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/utsunomiya.mp3", "宇都宮線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/tokaido.mp3", "東海道線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/yokosuka.mp3", "横須賀線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/chuou.mp3", "中央線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/joban.mp3", "常磐線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/keiyo.mp3", "京葉線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/sobu.mp3", "総武線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/musashino.mp3", "武蔵野線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/yamate.mp3", "山手線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/keihintohoku.mp3", "京浜東北線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/keihinegishi.mp3", "京浜東北・根岸線"], 
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/kawagoe.mp3", "川越線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/saikyo.mp3", "埼京線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/rinkai.mp3", "りんかい線"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/sotetsu.mp3", "相鉄線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/line/.mp3", ""], 
  
  
]

// 番線用音源
let bansen_num = [
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/1no.mp3", "1番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "2番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "3番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "4番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "5番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "6番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "7番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "8番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "9番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "10番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "11番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "12番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "13番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "14番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "15番線の"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "16番線の"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/1ni.mp3", "1番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "2番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "3番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "4番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "5番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "6番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "7番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "8番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "9番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "10番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "11番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "12番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "13番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "14番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "15番線に"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "16番線に"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/1wo.mp3", "1番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "2番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "3番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "4番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "5番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "6番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "7番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "8番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "9番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "10番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "11番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "12番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "13番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "14番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "15番線を"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "16番線を"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/1kara.mp3", "1番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "2番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "3番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "4番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "5番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "6番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "7番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "8番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "9番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "10番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "11番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "12番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "13番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "14番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "15番線から"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "16番線から"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/1.mp3", "1番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "2番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "3番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "4番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "5番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "6番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "7番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "8番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "9番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "10番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "11番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "12番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "13番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "14番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "15番線"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bansen/.mp3", "16番線"],
]

// 行き先
let buund_for = [
  
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_ikb.mp3",  "池袋方面行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_nipr.mp3",  "日暮里方面行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_sby.mp3",  "渋谷方面行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_sjk.mp3",  "新宿方面行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_sng.mp3",  "品川方面行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_tbt.mp3",  "田端方面行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_tokyo.mp3",  "東京方面行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_ueno.mp3",  "上野方面行きが"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_soto.mp3",  "山手線外回り"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/yamate_uchi.mp3",  "山手線内回り"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/ikebukuro.mp3",  "池袋"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/nippori.mp3",  "日暮里"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/shibuya.mp3",  "渋谷"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/shinjuku.mp3",  "新宿"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/shinagawa.mp3",  "品川"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/tabata.mp3",  "田端"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/tokyo.mp3",  "東京"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/ueno.mp3",  "上野"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/osaki.mp3",  "大崎"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/kagohara.mp3",  "籠原"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/fukaya.mp3",  "深谷"],
  ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/takasaki.mp3",  "高崎"],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/.mp3",  ""],
  // ["/Users/yuki_tajima/vagrant/ubuntu64_16/workspace/web_station_sound/sound/voicetext/bound/.mp3",  ""],
]
let atos =  atos_cross.concat(train_type, train_line, bansen_num, buund_for);